# Generated by Django 4.1.6 on 2023-04-02 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('주소', models.TextField()),
                ('면적', models.CharField(max_length=100)),
                ('가격', models.CharField(max_length=100)),
                ('종류', models.CharField(max_length=100)),
                ('층수', models.CharField(max_length=100)),
                ('입주가능일', models.CharField(max_length=100)),
                ('방수', models.CharField(max_length=100)),
                ('사용승인', models.CharField(max_length=100)),
                ('난방', models.CharField(max_length=100)),
                ('방향', models.CharField(max_length=100)),
                ('비고', models.CharField(max_length=100)),
                ('주차', models.CharField(max_length=100)),
                ('작성자', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='작성자', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
